---
name: Wx-Perl-TreeView
version: 0.01
author:
  - 'Mattia Barbon <mbarbon@cpan.org>'
abstract: virtual tree control interface
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::More: 0.5
  Wx: 0.26
provides:
  Wx::Perl::TreeView:
    file: lib/Wx/Perl/TreeView.pm
    version: 0.01
  Wx::Perl::TreeView::Model:
    file: lib/Wx/Perl/TreeView/Model.pm
  Wx::Perl::TreeView::SimpleModel:
    file: lib/Wx/Perl/TreeView/SimpleModel.pm
generated_by: Module::Build version 0.2807
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
